services:
  wordlee-database:
    container_name: user-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - user-service-postgresdb-data:/var/lib/postgresql/data
    networks:
      - user-service-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - user-service-network

networks:
  user-service-network:
    name: user-service-network
    driver: bridge

volumes:
  user-service-postgresdb-data:
    name: user-service-postgresdb-data
