services:
  wordlee-database:
    container_name: wordlee-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - wordlee-postgresdb-data:/var/lib/postgresql/data
    networks:
      - wordlee-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

networks:
  wordlee-network:
    name: wordlee-network
    driver: bridge

volumes:
  wordlee-postgresdb-data:
    name: wordlee-postgresdb-data